# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "design_spec.baml": "class DesignSpec {\n  summary string\n  screens Screen[]\n}\n\nclass Screen {\n  name string\n  description string\n  wireframe string   // Markdown, HTML, or text representation\n  components Component[]\n}\n\nclass Component {\n  name string\n  description string\n  code_snippet string\n  notes string\n}\n",
    "product_strategist.baml": "class BRD {\n  title string\n  description string\n  objectives string[]\n}",
}

def get_baml_files():
    return _file_map