# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class BRD(BaseModel):
    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    objectives: typing.List[str]

class Component(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    code_snippet: typing.Optional[str] = None
    notes: typing.Optional[str] = None

class DesignSpec(BaseModel):
    summary: typing.Optional[str] = None
    screens: typing.List["Screen"]

class Screen(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    wireframe: typing.Optional[str] = None
    components: typing.List["Component"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
