# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BRD": types.BRD,
    "stream_types.BRD": stream_types.BRD,

    "types.Component": types.Component,
    "stream_types.Component": stream_types.Component,

    "types.DesignSpec": types.DesignSpec,
    "stream_types.DesignSpec": stream_types.DesignSpec,

    "types.Screen": types.Screen,
    "stream_types.Screen": stream_types.Screen,


}